#
# FILE: evolutionary_mapping_config.yaml
# WORKING_DIRECTORY: Config
# PURPOSE: System configuration with educational framework integration
# CREATOR: Amos Wales - Progressive Framework Pioneer
# UPDATED: 20250819_Educational-Phase3-Integration
# STATUS: ✅ Universal Header System Compliant
# BREATHING_FRAMEWORK: 15 Systems ✅ | 615+ Tests ✅ | Educational Integration ✅
# PROGRESSIVE_ACADEMY: Foundation ✅ | Professional ✅ | Universal ✅ | Config Ready ✅
#

evolutionary_mapping:
  automation:
    auto_archive_old_versions: false
    auto_bridge_competency_gaps: true
    auto_generate_adaptations: true
    auto_update_discovery_index: true
  enabled: true
  features:
    cross_system_inheritance: true
    educational_archaeology: true
    intelligent_discovery: true
    lesson_evolution_detection: true
    student_progress_protection: true
  policies:
    enable_competency_bridging: true
    maintain_certification_validity: true
    never_delete_lessons: true
    preserve_student_progress: true
  thresholds:
    cross_system_relevance_minimum: 0.3
    discovery_recommendation_confidence: 0.9
    evolution_detection_sensitivity: 0.8
    student_protection_priority: critical
  version: '1.0'
system_profiles:
  system_1:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 1
  system_10:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 10
  system_11:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 11
  system_12:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 12
  system_13:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 15 system_14:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 14
  system_15:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 15
  system_2:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 2
  system_3:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 3
  system_4:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 4
  system_5:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 5
  system_6:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 6
  system_7:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 7
  system_8:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 8
  system_9:
    cross_system_compatibility: true
    inheritance_preferences: automatic
    lesson_adaptation_rules: system_specific
    system_id: 9
