#
# FILE: lesson_triggers.yaml
# WORKING_DIRECTORY: Config
# PURPOSE: Progressive Framework Academy educational lesson content
# CREATOR: Amos Wales - Progressive Framework Pioneer
# UPDATED: 20250819_Educational-Phase3-Integration
# STATUS: ✅ Universal Header System Compliant
# BREATHING_FRAMEWORK: 15 Systems ✅ | 615+ Tests ✅ | Educational Integration ✅
# PROGRESSIVE_ACADEMY: Foundation ✅ | Professional ✅ | Universal ✅ | Config Ready ✅
#

triggers:
- auto_index: true
  auto_save: true
  cross_system_analysis: true
  generation_delay: 5.0
  source_patterns:
  - '**/PROGRESSIVEPROJECT-SYSTEM-*.md'
  - '**/test_*.py'
  - '**/spec_*.md'
  target_systems:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  trigger_type: test_case_added
- auto_index: true
  auto_save: true
  cross_system_analysis: true
  generation_delay: 10.0
  source_patterns:
  - '**/PROGRESSIVEPROJECT-SYSTEM-*.md'
  target_systems:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  trigger_type: test_case_modified
- auto_index: true
  auto_save: true
  cross_system_analysis: true
  generation_delay: 15.0
  source_patterns:
  - '**/System_Specs/*.md'
  - '**/debugging_engines_specs.md'
  target_systems:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  trigger_type: system_specification_updated
